name: Tests

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run tests script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ secrets.AI_URL }}
          TOKEN: ${{ secrets.AI_TOKEN }}
          NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          chmod +x ci/tests/main.sh
          bash ci/tests/main.sh

